server:
  port: 12800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CSLINK?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 1
  mail:
    host: smtp.yeah.net
    username: cslink@yeah.net
    password: UTBTHODMSMLAYSXQ
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
#mybatis-plus:
#  configuration:
#
#  global-config:
#    db-config:
#      logic-delete-field: delFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
    - classpath*:/mapper/**/*Mapper.xml

token:
  header: Authorization
  secret: aflk2345utyipseruf23456hias
  expireTime: 120