server:
  port: 12800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CSLINK?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000
#mybatis-plus:
#  configuration:
#
#  global-config:
#    db-config:
#      logic-delete-field: delFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
    - classpath*"/mapper/**/*Mapper.xml